Portfolio: setup and mobile version skeleton
kingqabil/My-Portfolio pull request #1
Opened 2021-09-21 22:31 UTC by kingqabil

Parsed a Figma design to create a UI.
Use Flexbox to place elements in the page.
Build a personal portfolio site.
Use images and backgrounds to enhance the look of the website.

2021-09-21 23:57 UTC, Alexoid1 requested changes
Hi @kingqabil, @Sadqhabil 

Impressive project!
You are doing a great job so far, and the project is looking good.
- Follow Git-hub flow guidelines.
- No linters errors.
- Descriptive README.md file.

## Required Changes :recycle:
For the project to get approved, also implement the changes mentioned below.

## Optional suggestions
_Every comment with the [OPTIONAL] prefix is not crucial enough to stop the approval of this PR. However, I strongly recommend you to take them into account as they can make your code better._

Cheers and Happy coding!

Feel free to leave any questions or comments in the PR thread if something is not 100% clear.

Please, do not open a new Pull Request for re-reviews. You should use the same Pull Request submitted for the first review, either valid or invalid unless it is requested otherwise.

As described in the [Code reviews limits policy](https://microverse.zendesk.com/hc/en-us/articles/1500004088561) you have a limited number of reviews per project (check the exact number in your Dashboard). If you think that the code review was not fair, you can request a second opinion using [this form](https://airtable.com/shrQAqnBwek5a0O0s).

2021-09-21 23:57 UTC, Alexoid1 commented on index.html
> +    <div class="topnav">
- [ ] Replace `div` with `header` tag. This will make your code more semantic and also will add SEO support to the website.

2021-09-21 23:57 UTC, Alexoid1 commented on index.html
> +        </a>
- [ ] All this block of code has to be wrapped with a nav tag. This will make your code more semantic and also will add SEO support to the website.

2021-09-21 23:57 UTC, Alexoid1 commented on index.html
> +        <a class="icon">
- [ ] Replace `a` tag with a `button` tag.

2021-09-21 23:57 UTC, Alexoid1 commented on style.css
> +  width: 327px;
- [OPTIONAL] Please don't use fixed-width use percentage or media-queries in order to make your project responsive for the different mobile devices.
![Captura de pantalla_2021-09-21_18-49-40](https://user-images.githubusercontent.com/53111464/134262254-93dea07d-62e0-4606-b47c-9153cbdf2689.png)
**Mobile device: pixel2
Screen width: 411px**

2021-09-22 19:59 UTC, karvel-code approved these changes
Hi @kingqabil, 

Your project is complete!  There is nothing else to say other than... it's time to merge it :shipit: 
Congratulations! 🎉 

Cheers and Happy coding!👏👏👏

Feel free to leave any questions or comments in the PR thread if something is not 100% clear.

------
_As described in the [Code reviews limits policy](https://microverse.zendesk.com/hc/en-us/articles/1500004088561)  you have a limited number of reviews per project (check the exact number in your Dashboard). If you think that the code review was not fair, you can request a second opinion using [this form](https://airtable.com/shrQAqnBwek5a0O0s)._

2021-09-23 03:26 UTC, merged