Portfolio: details popup window
kingqabil/My-Portfolio pull request #12
Opened 2021-10-12 15:13 UTC by kingqabil

2021-10-12 15:49 UTC, carlos-ssh requested changes
Hi @kingqabil , 

Great work on making the changes requested by a previous reviewer 👏 
You've done well implementing some of the requested changes, but there are still some which aren't addressed yet.

![changesrequested](https://user-images.githubusercontent.com/22258274/136988551-b83cba2d-be20-41d1-b582-2d0d437c4017.gif)


 ## Required Changes ♻️
_Check the comments under the review._

## Optional suggestions

_Every comment with the [OPTIONAL] prefix won't stop the approval of this PR. However, I strongly recommend you to take them into account as they can make your code better. Some of them were simply missed by the previous reviewer and addressing them will really improve your application._


Cheers and Happy coding!👏👏👏

Feel free to leave any questions or comments in the PR thread if something is not 100% clear.

**_Please, do not open a new Pull Request for re-reviews. You should use the same Pull Request submitted for the first review, either valid or invalid unless it is requested otherwise._**


------
_As described in the [Code reviews limits policy](https://microverse.zendesk.com/hc/en-us/articles/1500004088561) you have only 3 code reviews per project. If you think that the code review was not fair, you can request a second opinion using [this form](https://airtable.com/shrQAqnBwek5a0O0s)._

2021-10-12 15:49 UTC, carlos-ssh commented on script.js
> +  // body.style.overflow = 'hidden';
- Remove commented code.

2021-10-12 15:49 UTC, carlos-ssh commented on README.md
Keep professionalism in your projects. 
- Kindly provide a description about the features implemented in your branch.

2021-10-12 15:49 UTC, carlos-ssh commented on script.js
> +// iterate through the items and listen for popupwindow click
[OPTIONAL]
- Remove commented code. Your code explains by itself what it do.

2021-10-12 15:49 UTC, carlos-ssh commented on script.js
- Provide the requested styles guidelines in your Figma template.
**Requested style:**
<img width="547" alt="Screen Shot 2021-10-12 at 10 42 55" src="https://user-images.githubusercontent.com/22258274/136987889-aded1611-8716-4a79-8aad-c5da999c3586.png">

#

**Yours:**
<img width="402" alt="Screen Shot 2021-10-12 at 10 46 34" src="https://user-images.githubusercontent.com/22258274/136988183-b824aa7a-c001-49d3-98a5-80ff7310ae41.png">

**_ Kindly check your paddings_**

2021-10-12 20:22 UTC, GzimAsani requested changes
# Hi @Sadqhabil         
Good job so far!
There are some issues that you still need to work on to go to the next project but you are almost there!

## To highlight:
- Good use of gitflow :+1: 

## Required Changes ♻️
- [ ] PR description should be used to write the changes that you've made in this pull request and to explain your work. Please add a more descriptive PR


## Optional suggestions
_Every comment with the [OPTIONAL] prefix is not crucial enough to stop the approval of this PR. However, I strongly recommend you to take them into account as they can make your code better._

You can also consider:
N/A

Cheers and Happy coding!👏👏👏

Feel free to leave any questions or comments in the PR thread if something is not 100% clear.

**_Please, do not open a new Pull Request for re-reviews. You should use the same Pull Request submitted for the first review, either valid or invalid unless it is requested otherwise._**

------
_As described in the [Code reviews limits policy](https://microverse.zendesk.com/hc/en-us/articles/1500004088561) you have a limited number of reviews per project (check the exact number in your Dashboard). If you think that the code review was not fair, you can request a second opinion using [this form](https://airtable.com/shrQAqnBwek5a0O0s)._

2021-10-12 20:22 UTC, GzimAsani commented on script.js
Please improve this section in order to match the figma project!
![Screenshot from 2021-10-12 22-20-18](https://user-images.githubusercontent.com/62705947/137023703-671b99b7-f332-4992-832a-cf4b180750cb.png)

2021-10-12 20:22 UTC, GzimAsani commented on README.md
- [ ] Please implement this requirement asked by the previous reviewer

2021-10-13 08:05 UTC, Mihndim2020 approved these changes
# STATUS: APPROVED!!!  🎉 🎉 🎉 :champagne: :champagne: :champagne:
Hi @kingqabil & @Lockless404, 

Your project is complete! Great work on making the changes requested by the previous reviewer. There is nothing else to say other than... it's time to merge it :shipit: 
Congratulations! 🎉 🎉 🎉 :champagne: :champagne: :champagne:

![Congratulations-Memes-FEATURED](https://user-images.githubusercontent.com/65852621/133696300-b506e476-dc1a-443e-935a-c6f434e788b6.jpg)

## Optional suggestions

_Check the comments under the review._

_Every comment with the [OPTIONAL] prefix won't stop the approval of this PR. However, I strongly recommend you to take them into account as they can make your code better. Some of them were simply missed by the previous reviewer and addressing them will really improve your application._


Cheers and Happy coding!👏👏👏

Feel free to leave any questions or comments in the PR thread if something is not 100% clear.


------
_As described in the [Code reviews limits policy](https://microverse.zendesk.com/hc/en-us/articles/1500004088561)  you have a limited number of reviews per project (check the exact number in your Dashboard). If you think that the code review was not fair, you can request a second opinion using [this form](https://airtable.com/shrQAqnBwek5a0O0s)._

2021-10-13 08:08 UTC, merged